name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2

      - name: build-app
        run: ci/build-app.sh

      - name: test-app
        run: ci/unit-test-app.sh
